package com.pulsechat.service;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.net.URI;
import java.util.Locale;
import java.util.Map;

@Service
public class CloudinaryService {
    private final Cloudinary cloud;
    private final long max;

    public CloudinaryService(
            @Value("${cloudinary.cloud-name}") String n,
            @Value("${cloudinary.api-key}") String k,
            @Value("${cloudinary.api-secret}") String s,
            @Value("${app.max-file-size}") long max
    ) {
        this.max = max;
        if (n.isBlank() || k.isBlank() || s.isBlank()) {
            cloud = null;
        } else {
            cloud = new Cloudinary(ObjectUtils.asMap(
                    "cloud_name", n,
                    "api_key", k,
                    "api_secret", s
            ));
        }
    }

    /**
     * Uploads arbitrary files while choosing the correct Cloudinary asset type.
     *
     * Images remain normal public image assets so chat previews work.
     * Videos/audio remain normal video assets so playback works.
     * PDFs and every other non-media file are uploaded as PRIVATE assets. Their
     * downloads are generated by CloudinaryDownloadService using a short-lived
     * signed private-download URL.
     */
    public UploadResult upload(MultipartFile f) throws IOException {
        if (cloud == null) {
            throw new IllegalStateException("Cloudinary is not configured.");
        }

        if (f == null || f.isEmpty()) {
            throw new IllegalArgumentException("Empty file.");
        }

        if (f.getSize() > max) {
            throw new IllegalArgumentException(
                    "File is too large. Maximum size is " + formatBytes(max) + "."
            );
        }

        String name = sanitizeFilename(f.getOriginalFilename());
        String mime = normalizeMime(f.getContentType());
        String resourceType = resolveResourceType(name, mime);
        boolean restricted = "image".equals(resourceType) && isPdf(name, mime)
                || "raw".equals(resourceType);

        Map<String, Object> options = new java.util.HashMap<>();
        options.put("resource_type", resourceType);
        options.put("folder", "pulsechat");
        options.put("use_filename", true);
        options.put("unique_filename", true);
        options.put("filename_override", name);

        if (restricted) {
            options.put("type", "private");
        }

        Map<?, ?> result = (Map<?, ?>) cloud.uploader().upload(
                f.getBytes(),
                options
        );

        return new UploadResult(
                (String) result.get("secure_url"),
                (String) result.get("public_id"),
                name,
                mime,
                f.getSize()
        );
    }

    /**
     * Copies a public remote HTTP(S) image/GIF/video into Cloudinary.
     * The browser therefore no longer needs to contact the original media host.
     */
    public RemoteUploadResult uploadRemoteUrl(String sourceUrl) throws IOException {
        if (cloud == null) {
            throw new IllegalStateException("Cloudinary is not configured.");
        }

        String url = sourceUrl == null ? "" : sourceUrl.trim();
        if (url.isBlank() || url.length() > 2048) {
            throw new IllegalArgumentException("Please provide a valid media URL.");
        }

        try {
            URI uri = URI.create(url);
            String scheme = uri.getScheme();
            if (!("http".equalsIgnoreCase(scheme) || "https".equalsIgnoreCase(scheme))) {
                throw new IllegalArgumentException("Only HTTP and HTTPS media links are supported.");
            }
            if (uri.getHost() == null || uri.getHost().isBlank()) {
                throw new IllegalArgumentException("The media URL has no valid host.");
            }
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Please provide a valid media URL.");
        }

        Map<String, Object> options = new java.util.HashMap<>();
        options.put("resource_type", "auto");
        options.put("folder", "pulsechat/linked-media");
        options.put("unique_filename", true);

        Map<?, ?> result = (Map<?, ?>) cloud.uploader().upload(url, options);

        String resourceType = String.valueOf(result.getOrDefault("resource_type", ""));
        if (!("image".equals(resourceType) || "video".equals(resourceType))) {
            throw new IllegalArgumentException("That link is not a supported image, GIF, or video.");
        }

        String format = String.valueOf(result.getOrDefault("format", ""));
        String mime = toMimeType(resourceType, format);
        String originalName = extractRemoteName(url, format);
        int width = number(result.get("width"));
        int height = number(result.get("height"));
        long bytes = longNumber(result.get("bytes"));

        return new RemoteUploadResult(
                (String) result.get("secure_url"),
                (String) result.get("public_id"),
                resourceType,
                format,
                mime,
                originalName,
                width,
                height,
                bytes
        );
    }

    private String resolveResourceType(String filename, String mime) {
        String lowerName = filename.toLowerCase(Locale.ROOT);

        if (isPdf(lowerName, mime)) {
            return "image";
        }

        if (mime.startsWith("image/")) {
            return "image";
        }

        if (mime.startsWith("video/") || mime.startsWith("audio/")) {
            return "video";
        }

        return "raw";
    }

    private boolean isPdf(String filename, String mime) {
        return "application/pdf".equals(mime)
                || filename.toLowerCase(Locale.ROOT).endsWith(".pdf");
    }

    private String sanitizeFilename(String original) {
        if (original == null || original.isBlank()) {
            return "file";
        }

        String name = original
                .replace('\\', '_')
                .replace('/', '_')
                .replaceAll("[\\p{Cntrl}]", "_")
                .replaceAll("[^a-zA-Z0-9._ -]", "_")
                .trim();

        if (name.isBlank() || ".".equals(name) || "..".equals(name)) {
            return "file";
        }

        return name.length() > 255 ? name.substring(0, 255) : name;
    }

    private String normalizeMime(String contentType) {
        if (contentType == null || contentType.isBlank()) {
            return "application/octet-stream";
        }

        String mime = contentType.toLowerCase(Locale.ROOT).trim();
        return mime.isBlank() ? "application/octet-stream" : mime;
    }

    private String toMimeType(String resourceType, String format) {
        if (format == null || format.isBlank()) {
            return "video".equals(resourceType) ? "video/mp4" : "image/*";
        }

        String f = format.toLowerCase(Locale.ROOT);
        if ("jpg".equals(f)) f = "jpeg";
        if ("svg".equals(f)) return "image/svg+xml";
        if ("webm".equals(f)) return "video/webm";
        if ("mov".equals(f)) return "video/quicktime";
        return ("video".equals(resourceType) ? "video/" : "image/") + f;
    }

    private String extractRemoteName(String sourceUrl, String format) {
        try {
            String path = URI.create(sourceUrl).getPath();
            if (path != null && !path.isBlank()) {
                String last = path.substring(path.lastIndexOf('/') + 1);
                if (!last.isBlank()) return sanitizeFilename(last);
            }
        } catch (Exception ignored) {
        }
        return "linked-media" + ((format == null || format.isBlank()) ? "" : "." + format);
    }

    private int number(Object value) {
        return value instanceof Number n ? n.intValue() : 0;
    }

    private long longNumber(Object value) {
        return value instanceof Number n ? n.longValue() : 0L;
    }

    private String formatBytes(long bytes) {
        if (bytes >= 1024L * 1024L) {
            return (bytes / (1024L * 1024L)) + " MB";
        }
        if (bytes >= 1024L) {
            return (bytes / 1024L) + " KB";
        }
        return bytes + " bytes";
    }

    public record UploadResult(
            String url,
            String publicId,
            String originalName,
            String mimeType,
            long size
    ) {
    }

    public record RemoteUploadResult(
            String url,
            String publicId,
            String resourceType,
            String format,
            String mimeType,
            String originalName,
            int width,
            int height,
            long size
    ) {
    }
}
